services:
  dapa_be:
    build:
      context: .
      dockerfile: Dockerfile.server
    container_name: dapa_backend
    depends_on:
        - dapa_pg
        - dapa_redis
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+asyncpg://${POSTGRES_USER}:${POSTGRES_PASSWORD}@dapa_pg:${POSTGRES_PORT}/${POSTGRES_DB}
      - REDIS_URL=redis://dapa_redis:6379
    networks:
      - dapa-network


  dapa_streamlit_fe:
      build:
        context: .
        dockerfile: Dockerfile.client
      container_name: dapa_streamlit
      ports:
        - "8088:8088"
      depends_on:
        - dapa_be
      env_file:
        - .env
      environment:
        - BACKEND_URL=http://dapa_backend:8080
      networks:
        - dapa-network
      develop:
        watch:
          - path: src/client/
            action: sync+restart
            target: /app/client/
          - path: src/schema/
            action: sync+restart
            target: /app/schema/
          - path: src/interface.py
            action: sync+restart
            target: /app/interface.py
  
  dapa_pg:
    image: postgres:latest
    container_name: dapa_pg
    ports:
      - "5432:5432"
    env_file:
      - .env
    networks:
      - dapa-network
    volumes:
      - pg_db_1:/var/lib/postgresql/data

  dapa_redis:
    image: redis:latest
    container_name: dapa_redis
    restart: always
    ports:
      - "6379:6379"
    networks:
      - dapa-network

volumes:
  pg_db_1:

networks:
  dapa-network:

# To build and run the app:
# docker compose up --build -d
# or for dev easy
# docker compose watch