FROM python:3.12.3-slim

WORKDIR /app

COPY requirements_client.txt ./
RUN pip install --no-cache-dir -r requirements_client.txt

COPY . .

EXPOSE 8088

HEALTHCHECK CMD curl --fail http://localhost:8088/_stcore/health

ENTRYPOINT ["streamlit", "run", "src/interface.py", "--server.port=8088", "--server.address=0.0.0.0"]