FROM python:3.12.3-slim

# log appears immediately
ENV PYTHONUNBUFFERED 1
WORKDIR /app

COPY requirements_server.txt ./
RUN pip install --no-cache-dir -r requirements_server.txt

COPY . .

EXPOSE 5050

HEALTHCHECK CMD curl --fail http://localhost:5050/_stcore/health

# Start the backend application
ENTRYPOINT ["uvicorn", "src.main:app", "--host", "0.0.0.0", "--port", "5050"]